services:
    - docker

before_install:
    - docker --version

addons:
  apt:
    packages:
      - docker-ce

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - image="mmornati/docker-ghostdbmigrate"
    - if [ -n "$TRAVIS_TAG" ]; then
      image="$image:$TRAVIS_TAG";
      fi
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker run -d --name blogmigrate -e NODE_ENV=production -e DB_CURRENT_VERSION=1.0.2 "$image"
    - echo "GhostMigrate available..."
script:
    - official-images/test/run.sh "$image"

after_script:
    - docker images
    - docker stop blogmigrate
    - docker rm blogmigrate

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$image";
